### ISSUE TITLE
decode function potential bug

### ISSUE THREAD

**Issue by ali-naq-v** [kizzx2/sbe-python#14]
Hi guys, just wanted to run this by here. Would the body of the second if statement ever be hit? Doesn't seem like it would. Is this a bug?

```python
            if isinstance(f, Group):
                assert cursor.val >= header.value['blockLength']
                if cursor.val < header.value['blockLength']:
                    format_str_parts.append(str(header.value['blockLength'] - cursor.val) + 'x')
```

[Link](https://github.com/kizzx2/sbe-python/blob/master/sbe/__init__.py#L502) to line of the code

**Comment by baryluk** [comment]
In 0.2.8 it was:

```python3
         if isinstance(f, Group):
                assert cursor.val <= header.value['blockLength']
                if cursor.val < header.value['blockLength']:
                    format_str_parts.append(str(header.value['blockLength'] - cursor.val) + 'x')
```

**Comment by baryluk** [comment]
There is open PR about this https://github.com/kizzx2/sbe-python/pull/5/files

**Comment by ali-naq-v** [comment]
looks good in the PR https://github.com/kizzx2/sbe-python/pull/5
closing

**Comment by ali-naq-v** [comment]
looks good in the PR https://github.com/kizzx2/sbe-python/pull/5
closing
