### ISSUE TITLE
Errors while parsing B3 exchange schema

### ISSUE THREAD

**Issue by gaurang-lakesidetrading** [kizzx2/sbe-python#23]
The schema is located here [https://www.b3.com.br/data/files/8C/11/68/80/2DD3B810EE51F2B8AC094EA8/b3-entrypoint-messages-8.0.0.xml](url)

` with open('b3-entrypoint-messages-8.0.0.xml', 'r') as f: `
`    oe_schema = sbe.Schema.parse(f)`

`Traceback (most recent call last):`
`  File "b3_messages.py", line 131, in <module>`
`    oe_schema = sbe.Schema.parse(f)`
`  File "/usr/local/lib/python3.6/site-packages/sbe/__init__.py", line 475, in parse`
`    rv = _parse_schema(f)`
`  File "/usr/local/lib/python3.6/site-packages/sbe/__init__.py", line 1048, in _parse_schema`
`    encoding_type = stack[0].types[attrs['encodingType']]`
`KeyError: 'uint8EnumEncoding'`

**Comment by kizzx2** [comment]
Thanks for the report. Fixed in `0.4.1`
